@HostAddress = http://localhost:5053

POST {{HostAddress}}/api/projects
Content-Type: application/json

{
    "name": "Painel Administrativo",
    "description": "Dashboard interno com relatórios e gráficos de desempenho.",
    "startDate": "2025-08-05",
    "endDate": "2025-12-20"
}

###
GET {{HostAddress}}/api/projects
Accept: application/json

###
POST {{HostAddress}}/api/tasks
Content-Type: application/json

{
    "title": "Testes de integração",
    "description": "Implementar testes automáticos para validação de fluxos principais",
    "status": "DOING",
    "priority": "HIGH",
    "dueDate": "2025-10-25",
    "projectId": 2
  }
###
GET {{HostAddress}}/api/tasks?projectId=4&status=doing&priority=medium
Content-Type: application/json

###
PUT {{HostAddress}}/api/tasks/{id}/status
Content-Type: application/json

###
DELETE  {{HostAddress}}/api//tasks/{id}
Content-Type: application/json